CREATE TABLE pessoa (
	codigo BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	Nome VARCHAR(50) NOT NULL,
	Ativo BOOLEAN NOT NULL,
	Lagradouro VARCHAR(50) NOT NULL,
	Numero VARCHAR(10) NOT NULL, 
	Complemento VARCHAR (50),
	Bairro VARCHAR(50) NOT NULL,
	CEP VARCHAR(10) NOT NULL,
	Cidade VARCHAR(30) NOT NULL,
	Estado Varchar(50)
)ENGINE=InnoDB DEFAULT CHARSET=UTF8;